# .github/workflows/app.yaml
name: PyTest
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry
      - name: install dependancies
        run: |
          poetry install
      - name: Others dependancies
        run: |
          bash otherRequirements.sh
      - name: Run test suite
        run: |
          poetry run pytest -v
      - name: Run test suite
        run: |
          # poetry run pylint *.py
